// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlDTMtOTD78EteFEL4ijV2uz0-gqfQl4g',
    appId: '1:974503796179:web:4349e879bd90655b646326',
    messagingSenderId: '974503796179',
    projectId: 'therapymassage-mobileapp',
    authDomain: 'therapymassage-mobileapp.firebaseapp.com',
    storageBucket: 'therapymassage-mobileapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT6uW7dlo-WsSlXOHJcAotixJSPo5dimc',
    appId: '1:974503796179:android:98d7022e6a8c38e3646326',
    messagingSenderId: '974503796179',
    projectId: 'therapymassage-mobileapp',
    storageBucket: 'therapymassage-mobileapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7f3fy3iyMORon7N-9KYcTvz7jPcsn0ck',
    appId: '1:974503796179:ios:5f1f41dfc636a5b4646326',
    messagingSenderId: '974503796179',
    projectId: 'therapymassage-mobileapp',
    storageBucket: 'therapymassage-mobileapp.firebasestorage.app',
    iosBundleId: 'com.therapymassage.app',
  );
}
